from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(800, 600)
		MainWindow.setMinimumSize(QtCore.QSize(800, 600))
		MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/resources/resources/main.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		MainWindow.setStyleSheet("QMainWindow{\n"
		                         "font: 10pt  \"Andalus\";\n"
		                         "}\n"
		                         "QStackedWidget{\n"
		                         "font: 12pt  \"Andalus\";\n"
		                         "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(55, 150, 110, 217), stop:1 rgba(255, 255, 255, 255));\n"
		                         "}\n"
		                         "QLabel{\n"
		                         "color: rgb(0, 85, 127);\n"
		                         "font: 16pt \"Times New Roman\";\n"
		                         "}\n"
		                         "QPushButton{\n"
		                         "font: 75 14pt \"MS Serif\";\n"
		                         "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(116, 94, 159, 93), stop:1 rgba(255, 255, 255, 255));\n"
		                         "border-radius: 10px;\n"
		                         "min-width: 250px;\n"
		                         "min-height:50px;\n"
		                         "border: None;\n"
		                         "}\n"
		                         "QPushButton::hover{\n"
		                         "background-color: rgb(0, 0, 255);\n"
		                         "color: rgb(255, 255, 255);\n"
		                         "border: None;\n"
		                         "}\n"
		                         "QPushButton::pressed{\n"
		                         "background-color: rgb(255, 0, 0);\n"
		                         "border: None;\n"
		                         "}\n"
		                         "QLineEdit{\n"
		                         "font: 12pt  \"Andalus\";\n"
		                         "border-radius: 10px;\n"
		                         "min-height:50px\n"
		                         "}\n"
		                         "QTableWidget{\n"
		                         "font: 12pt \"Andalus\";\n"
		                         "}\n"
		                         "")
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout.setObjectName("gridLayout")
		self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
		self.stackedWidget.setObjectName("stackedWidget")
		self.page = QtWidgets.QWidget()
		self.page.setObjectName("page")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.label_5 = QtWidgets.QLabel(self.page)
		self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
		self.label_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_5.setObjectName("label_5")
		self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem)
		self.label_10 = QtWidgets.QLabel(self.page)
		self.label_10.setMinimumSize(QtCore.QSize(50, 50))
		self.label_10.setMaximumSize(QtCore.QSize(50, 50))
		self.label_10.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_10.setText("")
		self.label_10.setScaledContents(True)
		self.label_10.setAlignment(QtCore.Qt.AlignCenter)
		self.label_10.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_10.setObjectName("label_10")
		self.horizontalLayout_5.addWidget(self.label_10)
		self.pushButton = QtWidgets.QPushButton(self.page)
		self.pushButton.setMinimumSize(QtCore.QSize(250, 50))
		self.pushButton.setMaximumSize(QtCore.QSize(250, 16777215))
		self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.pushButton.setIconSize(QtCore.QSize(50, 50))
		self.pushButton.setAutoDefault(True)
		self.pushButton.setDefault(True)
		self.pushButton.setObjectName("pushButton")
		self.horizontalLayout_5.addWidget(self.pushButton)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem1)
		self.gridLayout_2.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.label_9 = QtWidgets.QLabel(self.page)
		self.label_9.setMaximumSize(QtCore.QSize(100, 100))
		self.label_9.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_9.setText("")
		self.label_9.setPixmap(QtGui.QPixmap(":/resources/resources/login.png"))
		self.label_9.setScaledContents(True)
		self.label_9.setAlignment(QtCore.Qt.AlignCenter)
		self.label_9.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_9.setObjectName("label_9")
		self.horizontalLayout_3.addWidget(self.label_9)
		self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
		self.lineEdit = QtWidgets.QLineEdit(self.page)
		self.lineEdit.setEnabled(True)
		self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
		self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
		self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.lineEdit.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
		self.lineEdit.setInputMask("")
		self.lineEdit.setText("")
		self.lineEdit.setMaxLength(255)
		self.lineEdit.setClearButtonEnabled(True)
		self.lineEdit.setObjectName("lineEdit")
		self.gridLayout_2.addWidget(self.lineEdit, 2, 0, 1, 1)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.label_6 = QtWidgets.QLabel(self.page)
		self.label_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_6.setObjectName("label_6")
		self.horizontalLayout_4.addWidget(self.label_6)
		self.pushButton_2 = QtWidgets.QPushButton(self.page)
		self.pushButton_2.setMinimumSize(QtCore.QSize(250, 50))
		self.pushButton_2.setMaximumSize(QtCore.QSize(250, 16777215))
		self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
		self.pushButton_2.setDefault(True)
		self.pushButton_2.setObjectName("pushButton_2")
		self.horizontalLayout_4.addWidget(self.pushButton_2)
		self.gridLayout_2.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)
		self.userpassword_lineedit = QtWidgets.QLineEdit(self.page)
		self.userpassword_lineedit.setMinimumSize(QtCore.QSize(50, 50))
		self.userpassword_lineedit.setFocusPolicy(QtCore.Qt.StrongFocus)
		self.userpassword_lineedit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.userpassword_lineedit.setAutoFillBackground(False)
		self.userpassword_lineedit.setMaxLength(255)
		self.userpassword_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
		self.userpassword_lineedit.setClearButtonEnabled(True)
		self.userpassword_lineedit.setObjectName("userpassword_lineedit")
		self.gridLayout_2.addWidget(self.userpassword_lineedit, 4, 0, 1, 1)
		self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.label_7 = QtWidgets.QLabel(self.page)
		self.label_7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_7.setObjectName("label_7")
		self.horizontalLayout_6.addWidget(self.label_7)
		self.pushButton_3 = QtWidgets.QPushButton(self.page)
		self.pushButton_3.setMinimumSize(QtCore.QSize(250, 50))
		self.pushButton_3.setMaximumSize(QtCore.QSize(250, 16777215))
		self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.pushButton_3.setDefault(True)
		self.pushButton_3.setObjectName("pushButton_3")
		self.horizontalLayout_6.addWidget(self.pushButton_3)
		self.gridLayout_2.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)
		self.label_4 = QtWidgets.QLabel(self.page)
		self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
		self.label_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_4.setObjectName("label_4")
		self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
		self.stackedWidget.addWidget(self.page)
		self.page_2 = QtWidgets.QWidget()
		self.page_2.setObjectName("page_2")
		self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.name_lineedit = QtWidgets.QLineEdit(self.page_2)
		self.name_lineedit.setMinimumSize(QtCore.QSize(50, 50))
		self.name_lineedit.setFocusPolicy(QtCore.Qt.StrongFocus)
		self.name_lineedit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.name_lineedit.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
		self.name_lineedit.setMaxLength(255)
		self.name_lineedit.setClearButtonEnabled(True)
		self.name_lineedit.setObjectName("name_lineedit")
		self.gridLayout_4.addWidget(self.name_lineedit, 2, 0, 1, 1)
		self.name_label = QtWidgets.QLabel(self.page_2)
		self.name_label.setMaximumSize(QtCore.QSize(16777215, 30))
		font = QtGui.QFont()
		font.setFamily("Andalus")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.name_label.setFont(font)
		self.name_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.name_label.setScaledContents(False)
		self.name_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.name_label.setObjectName("name_label")
		self.gridLayout_4.addWidget(self.name_label, 1, 0, 1, 1)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem2)
		self.label_11 = QtWidgets.QLabel(self.page_2)
		self.label_11.setMinimumSize(QtCore.QSize(50, 50))
		self.label_11.setMaximumSize(QtCore.QSize(50, 50))
		self.label_11.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_11.setText("")
		self.label_11.setScaledContents(True)
		self.label_11.setAlignment(QtCore.Qt.AlignCenter)
		self.label_11.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_11.setObjectName("label_11")
		self.horizontalLayout_2.addWidget(self.label_11)
		self.ok_button_3 = QtWidgets.QPushButton(self.page_2)
		self.ok_button_3.setMinimumSize(QtCore.QSize(250, 50))
		self.ok_button_3.setMaximumSize(QtCore.QSize(250, 16777215))
		self.ok_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.ok_button_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.ok_button_3.setAutoDefault(False)
		self.ok_button_3.setDefault(True)
		self.ok_button_3.setObjectName("ok_button_3")
		self.horizontalLayout_2.addWidget(self.ok_button_3)
		spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem3)
		self.verticalLayout.addLayout(self.horizontalLayout_2)
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.label_8 = QtWidgets.QLabel(self.page_2)
		self.label_8.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_8.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_8.setObjectName("label_8")
		self.horizontalLayout_7.addWidget(self.label_8)
		self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
		self.pushButton_4.setMinimumSize(QtCore.QSize(250, 50))
		self.pushButton_4.setMaximumSize(QtCore.QSize(250, 16777215))
		self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.pushButton_4.setDefault(True)
		self.pushButton_4.setObjectName("pushButton_4")
		self.horizontalLayout_7.addWidget(self.pushButton_4)
		self.verticalLayout.addLayout(self.horizontalLayout_7)
		self.gridLayout_4.addLayout(self.verticalLayout, 12, 0, 1, 1)
		self.password_label = QtWidgets.QLabel(self.page_2)
		self.password_label.setMaximumSize(QtCore.QSize(16777215, 30))
		font = QtGui.QFont()
		font.setFamily("Andalus")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.password_label.setFont(font)
		self.password_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.password_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.password_label.setObjectName("password_label")
		self.gridLayout_4.addWidget(self.password_label, 3, 0, 1, 1)
		self.password_lineedit = QtWidgets.QLineEdit(self.page_2)
		self.password_lineedit.setMinimumSize(QtCore.QSize(50, 50))
		self.password_lineedit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.password_lineedit.setText("")
		self.password_lineedit.setMaxLength(255)
		self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
		self.password_lineedit.setClearButtonEnabled(True)
		self.password_lineedit.setObjectName("password_lineedit")
		self.gridLayout_4.addWidget(self.password_lineedit, 4, 0, 1, 1)
		self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.label = QtWidgets.QLabel(self.page_2)
		self.label.setMaximumSize(QtCore.QSize(100, 100))
		self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label.setText("")
		self.label.setPixmap(QtGui.QPixmap(":/resources/resources/profile.png"))
		self.label.setScaledContents(True)
		self.label.setAlignment(QtCore.Qt.AlignCenter)
		self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label.setObjectName("label")
		self.horizontalLayout_9.addWidget(self.label)
		self.gridLayout_4.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
		self.label_2 = QtWidgets.QLabel(self.page_2)
		self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
		self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_2.setObjectName("label_2")
		self.gridLayout_4.addWidget(self.label_2, 10, 0, 1, 1)
		self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
		self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
		self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.lineEdit_2.setMaxLength(255)
		self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
		self.lineEdit_2.setClearButtonEnabled(True)
		self.lineEdit_2.setObjectName("lineEdit_2")
		self.gridLayout_4.addWidget(self.lineEdit_2, 11, 0, 1, 1)
		self.stackedWidget.addWidget(self.page_2)
		self.page_3 = QtWidgets.QWidget()
		self.page_3.setObjectName("page_3")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.password_label_2 = QtWidgets.QLabel(self.page_3)
		self.password_label_2.setMaximumSize(QtCore.QSize(16777215, 50))
		font = QtGui.QFont()
		font.setFamily("Andalus")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.password_label_2.setFont(font)
		self.password_label_2.setMouseTracking(False)
		self.password_label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.password_label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.password_label_2.setObjectName("password_label_2")
		self.gridLayout_3.addWidget(self.password_label_2, 5, 0, 1, 1)
		self.lineEdit_4 = QtWidgets.QLineEdit(self.page_3)
		self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 50))
		self.lineEdit_4.setFocusPolicy(QtCore.Qt.StrongFocus)
		self.lineEdit_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.lineEdit_4.setMaxLength(255)
		self.lineEdit_4.setClearButtonEnabled(True)
		self.lineEdit_4.setObjectName("lineEdit_4")
		self.gridLayout_3.addWidget(self.lineEdit_4, 4, 0, 1, 1)
		self.username_label = QtWidgets.QLabel(self.page_3)
		self.username_label.setMaximumSize(QtCore.QSize(16777215, 50))
		font = QtGui.QFont()
		font.setFamily("Andalus")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.username_label.setFont(font)
		self.username_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.username_label.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.username_label.setWordWrap(True)
		self.username_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.username_label.setObjectName("username_label")
		self.gridLayout_3.addWidget(self.username_label, 3, 0, 1, 1)
		self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_10.setObjectName("horizontalLayout_10")
		self.label_3 = QtWidgets.QLabel(self.page_3)
		self.label_3.setMaximumSize(QtCore.QSize(100, 100))
		self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_3.setText("")
		self.label_3.setPixmap(QtGui.QPixmap(":/resources/resources/password.png"))
		self.label_3.setScaledContents(True)
		self.label_3.setAlignment(QtCore.Qt.AlignCenter)
		self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_3.setObjectName("label_3")
		self.horizontalLayout_10.addWidget(self.label_3)
		self.gridLayout_3.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
		self.lineEdit_3 = QtWidgets.QLineEdit(self.page_3)
		self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
		self.lineEdit_3.setFocusPolicy(QtCore.Qt.StrongFocus)
		self.lineEdit_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.lineEdit_3.setMaxLength(255)
		self.lineEdit_3.setClearButtonEnabled(True)
		self.lineEdit_3.setObjectName("lineEdit_3")
		self.gridLayout_3.addWidget(self.lineEdit_3, 2, 0, 1, 1)
		self.lineEdit_5 = QtWidgets.QLineEdit(self.page_3)
		self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
		self.lineEdit_5.setFocusPolicy(QtCore.Qt.StrongFocus)
		self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.lineEdit_5.setMaxLength(255)
		self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
		self.lineEdit_5.setClearButtonEnabled(True)
		self.lineEdit_5.setObjectName("lineEdit_5")
		self.gridLayout_3.addWidget(self.lineEdit_5, 6, 0, 1, 1)
		self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.getdata_button = QtWidgets.QPushButton(self.page_3)
		self.getdata_button.setMinimumSize(QtCore.QSize(250, 50))
		self.getdata_button.setMaximumSize(QtCore.QSize(250, 16777215))
		font = QtGui.QFont()
		font.setFamily("Levenim MT")
		font.setPointSize(14)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(9)
		self.getdata_button.setFont(font)
		self.getdata_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.getdata_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/resources/resources/show-password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.getdata_button.setIcon(icon1)
		self.getdata_button.setIconSize(QtCore.QSize(50, 40))
		self.getdata_button.setAutoDefault(False)
		self.getdata_button.setDefault(True)
		self.getdata_button.setFlat(False)
		self.getdata_button.setObjectName("getdata_button")
		self.horizontalLayout_8.addWidget(self.getdata_button)
		self.encryptdata_button = QtWidgets.QPushButton(self.page_3)
		self.encryptdata_button.setMinimumSize(QtCore.QSize(250, 50))
		self.encryptdata_button.setMaximumSize(QtCore.QSize(250, 16777215))
		font = QtGui.QFont()
		font.setFamily("Levenim MT")
		font.setPointSize(14)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(9)
		self.encryptdata_button.setFont(font)
		self.encryptdata_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.encryptdata_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/resources/resources/data-protection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.encryptdata_button.setIcon(icon2)
		self.encryptdata_button.setIconSize(QtCore.QSize(50, 40))
		self.encryptdata_button.setAutoDefault(False)
		self.encryptdata_button.setDefault(True)
		self.encryptdata_button.setFlat(False)
		self.encryptdata_button.setObjectName("encryptdata_button")
		self.horizontalLayout_8.addWidget(self.encryptdata_button)
		self.label_12 = QtWidgets.QLabel(self.page_3)
		self.label_12.setMinimumSize(QtCore.QSize(50, 50))
		self.label_12.setMaximumSize(QtCore.QSize(50, 50))
		self.label_12.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
		self.label_12.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.label_12.setText("")
		self.label_12.setScaledContents(True)
		self.label_12.setAlignment(QtCore.Qt.AlignCenter)
		self.label_12.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_12.setObjectName("label_12")
		self.horizontalLayout_8.addWidget(self.label_12)
		self.gridLayout_3.addLayout(self.horizontalLayout_8, 8, 0, 1, 1)
		self.accountname_label = QtWidgets.QLabel(self.page_3)
		self.accountname_label.setMaximumSize(QtCore.QSize(16777215, 50))
		font = QtGui.QFont()
		font.setFamily("Andalus")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.accountname_label.setFont(font)
		self.accountname_label.setMouseTracking(False)
		self.accountname_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.accountname_label.setStyleSheet("")
		self.accountname_label.setTextFormat(QtCore.Qt.AutoText)
		self.accountname_label.setScaledContents(True)
		self.accountname_label.setWordWrap(True)
		self.accountname_label.setIndent(-1)
		self.accountname_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.accountname_label.setObjectName("accountname_label")
		self.gridLayout_3.addWidget(self.accountname_label, 1, 0, 1, 1)
		self.stackedWidget.addWidget(self.page_3)
		self.page_4 = QtWidgets.QWidget()
		self.page_4.setObjectName("page_4")
		self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
		self.gridLayout_5.setObjectName("gridLayout_5")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.pushButton_6 = QtWidgets.QPushButton(self.page_4)
		self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
		self.pushButton_6.setMaximumSize(QtCore.QSize(50, 50))
		self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.pushButton_6.setAutoFillBackground(False)
		self.pushButton_6.setStyleSheet("QPushButton{\n"
		                                "background-color: None;\n"
		                                "max-width:50px;\n"
		                                "min-width:50px;\n"
		                                "border: None;\n"
		                                "outline: None;\n"
		                                "}")
		self.pushButton_6.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/resources/resources/goback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButton_6.setIcon(icon3)
		self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
		self.pushButton_6.setFlat(True)
		self.pushButton_6.setObjectName("pushButton_6")
		self.horizontalLayout.addWidget(self.pushButton_6)
		spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem4)
		self.label_13 = QtWidgets.QLabel(self.page_4)
		self.label_13.setMinimumSize(QtCore.QSize(0, 0))
		self.label_13.setMaximumSize(QtCore.QSize(100, 100))
		self.label_13.setText("")
		self.label_13.setPixmap(QtGui.QPixmap(":/resources/resources/view_password.png"))
		self.label_13.setScaledContents(True)
		self.label_13.setAlignment(QtCore.Qt.AlignCenter)
		self.label_13.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.label_13.setObjectName("label_13")
		self.horizontalLayout.addWidget(self.label_13)
		spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem5)
		self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
		self.tableWidget = QtWidgets.QTableWidget(self.page_4)
		self.tableWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.tableWidget.setAutoFillBackground(True)
		self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
		self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
		self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
		self.tableWidget.setDragEnabled(True)
		self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
		self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
		self.tableWidget.setRowCount(0)
		self.tableWidget.setColumnCount(4)
		self.tableWidget.setObjectName("tableWidget")
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(3, item)
		self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
		self.tableWidget.horizontalHeader().setMinimumSectionSize(125)
		self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
		self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
		self.tableWidget.verticalHeader().setDefaultSectionSize(35)
		self.tableWidget.verticalHeader().setMinimumSectionSize(35)
		self.gridLayout_5.addWidget(self.tableWidget, 1, 0, 1, 1)
		self.stackedWidget.addWidget(self.page_4)
		self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
		self.menubar.setObjectName("menubar")
		self.menuOptions = QtWidgets.QMenu(self.menubar)
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(11)
		self.menuOptions.setFont(font)
		self.menuOptions.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.menuOptions.setTearOffEnabled(False)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(":/resources/resources/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.menuOptions.setIcon(icon4)
		self.menuOptions.setObjectName("menuOptions")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.actiondelete = QtWidgets.QAction(MainWindow)
		self.actiondelete.setObjectName("actiondelete")
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap(":/resources/resources/rubbish-bin-delete-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actiondelete.setIcon(icon6)
		self.actionLog_out = QtWidgets.QAction(MainWindow)
		self.actionLog_out.setObjectName("actionLog_out")
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap(":/resources/resources/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionLog_out.setIcon(icon7)
		self.actionExit = QtWidgets.QAction(MainWindow)
		self.actionExit.setObjectName("actionExit")
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap(":/resources/resources/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionExit.setIcon(icon8)
		self.actionexport = QtWidgets.QAction(MainWindow)
		self.actionexport.setObjectName("actionexport")
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap(":/resources/resources/cloud-computing.png") , QtGui.QIcon.Normal , QtGui.QIcon.Off)
		self.actionexport.setIcon(icon9)
		self.menuOptions.addAction(self.actiondelete)
		self.menuOptions.addAction(self.actionexport)
		self.menuOptions.addSeparator()
		self.menuOptions.addAction(self.actionLog_out)
		self.menuOptions.addSeparator()
		self.menuOptions.addAction(self.actionExit)
		self.menubar.addAction(self.menuOptions.menuAction())


		self.menubar.hide()
		reg_ex = QtCore.QRegExp("^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w+[.]\w+[a-z]$")
		validator = QtGui.QRegExpValidator(reg_ex)
		self.lineEdit.setValidator(validator)
		self.name_lineedit.setValidator(validator)
		view = QtGui.QIcon(QtGui.QPixmap(":/resources/resources/eye-close-up.png"))
		self.action = QtWidgets.QAction(view , "Show Password" , self.userpassword_lineedit)
		self.action.setCheckable(True)
		self.userpassword_lineedit.addAction(self.action , QtWidgets.QLineEdit.TrailingPosition)
		self.password_lineedit.addAction(self.action , QtWidgets.QLineEdit.TrailingPosition)
		self.lineEdit_5.addAction(self.action , QtWidgets.QLineEdit.TrailingPosition)
		view2 = QtGui.QIcon(QtGui.QPixmap(":/resources/resources/user.png"))
		view3 = QtGui.QIcon(QtGui.QPixmap(":/resources/resources/key.png"))
		view4 = QtGui.QIcon(QtGui.QPixmap(":/resources/resources/world.png"))
		self.lineEdit.addAction(view2 , QtWidgets.QLineEdit.LeadingPosition)
		self.name_lineedit.addAction(view2 , QtWidgets.QLineEdit.LeadingPosition)
		self.userpassword_lineedit.addAction(view3 , QtWidgets.QLineEdit.LeadingPosition)
		self.password_lineedit.addAction(view3 , QtWidgets.QLineEdit.LeadingPosition)
		self.lineEdit_2.addAction(view3 , QtWidgets.QLineEdit.LeadingPosition)
		self.lineEdit_4.addAction(view2 , QtWidgets.QLineEdit.LeadingPosition)
		self.lineEdit_5.addAction(view3 , QtWidgets.QLineEdit.LeadingPosition)
		self.lineEdit_3.addAction(view4 , QtWidgets.QLineEdit.LeadingPosition)
		shadow_label = QtWidgets.QGraphicsDropShadowEffect()
		shadow_label.setBlurRadius(0)
		self.label.setGraphicsEffect(shadow_label)
		shadow_label_3 = QtWidgets.QGraphicsDropShadowEffect()
		shadow_label_3.setBlurRadius(0)
		self.label_3.setGraphicsEffect(shadow_label_3)
		shadow_label_9 = QtWidgets.QGraphicsDropShadowEffect()
		shadow_label_9.setBlurRadius(0)
		self.label_9.setGraphicsEffect(shadow_label_9)
		shadow_label_13 = QtWidgets.QGraphicsDropShadowEffect()
		shadow_label_13.setBlurRadius(0)
		self.label_13.setGraphicsEffect(shadow_label_13)
		reg = QtCore.QRegExp("^[A-Za-z0-9 ]*$")
		val = QtGui.QRegExpValidator(reg)
		self.lineEdit_3.setValidator(val)
		account_name = ["Swayam" , "Rediff Mail" , "Quikr" , "OLX" , "Voot" , "Wynk" , "Zoho Mail" , "AOL Mail" ,
		                "Outlook" , "Ebay" , "Blogspot" , "Microsoft" , "Apple" , "ShopClues" , "Linux" , "Windows" ,
		                "TOI" , "Ace2three" , "IMDB" , "Cricbuzz" , "Wikipedia" , "AliExpress" , "MySpace" , "Flickr" ,
		                "Photobucket" , "Digg" , "Ning" , "Yelp" , "Tagged" , "Squidoo" , "Scribd" , "StumbleUpon" ,
		                "Hi5" , "Bebo" , "MyYearbook" , "Technorati" , "P.Kaboodle" , "Friendster" , "Flixster" ,
		                "Xanga" , "Epinions" , "Plaxo" , "MyBlogLog" , "Yuku" , "MetaFilter" , "BlackPlanet" , "Care2" ,
		                "GetSatisfaction" , "FriendFeed" , "ClipMarks" , "CafeMom" , "NewsVine" , "Omgili" , "Gigya" ,
		                "Ballhype" , "Revver" , "Ping" , "Tribe" , "Magnify" , "Diigo" , "DZone" , "XingFaves" ,
		                "TwitPic" , "Ecademy" , "Twine" , "Buzznet" , "Pinterest" , "Snapchat" , "Baidu Tieba" ,
		                "Skype" , "Google+" , "Hangout" , "Orkut" , "Quora" , "Reddit" , "Stack Overflow" , "Yahoo" ,
		                "Uber Eat" , "Zomato" , "Swiggy" , "Uber" , "OLA" , "Sony Liv" , "Hotstar" , "Flipkart" ,
		                "Amazon" , "IRCTC Rail Connect" , "DigiLocker" , "ERP" , "Internshala" , "Linkedin" , "Zoom" ,
		                "Mi Account" , "Clash of Clans" , "VK" , "Telegram" , "Kakao Talk" , "Viber" , "Line" ,
		                "Gmail" , "Spotify" , "Jio Saavn" , "Gaana" , "Facebook" , "YouTube" , "WhatsApp" ,
		                "Messenger" , "WeChat" , "QQ" , "Instagram" , "QZone" , "Tumblr" , "Twitter" , "Triller" ,
		                "WT Social" , "Valence" , "Flip" , "Popbase" , "Elpha" , "Yubo" , "Peanut" , "HouseParty" ,
		                "Caffeine" , "Steemit" , "Goodreads" , "Twitch" , "CaringBridge" , "WattPad" , "Crunchyroll" ,
		                "Soundcloud" , "Mocospace" , "CouchSurfing" , "italki" , "Medium" , "Ello" , "Vimeo" , "Giphy" ,
		                "Tribe" , "Kuaishou" , "Imgur" , "Influenster" , "FilmAffinity" , "Open Diary" , "Bubbly"]
		completer = QtWidgets.QCompleter(account_name)
		completer.setCaseSensitivity(False)
		completer.setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
		self.lineEdit_3.setCompleter(completer)

		self.sync_decrypt_label = QtWidgets.QLabel()
		self.sync_decrypt_label.setStyleSheet("QLabel{\n"
		                                      "min-width:10px;\n"
		                                      "max-width:20px;\n"
		                                      "min-height:10px;\n"
		                                      "max-height:20px;\n"
		                                      "}")
		self.sync_decrypt_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.sync_decrypt_label.setText("")
		self.sync_decrypt_label.setToolTip("Decrypting Passwords")
		self.sync_decrypt_label.setScaledContents(True)
		self.sync_decrypt_label.setAlignment(QtCore.Qt.AlignCenter)
		self.sync_decrypt_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.sync_decrypt_label.setObjectName("sync_decrypt_label")
		self.statusbar.addWidget(self.sync_decrypt_label)
		self.sync_decrypt_label.hide()

		self.about_button = QtWidgets.QPushButton()
		self.about_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.about_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.about_button.setAutoFillBackground(False)
		self.about_button.setStyleSheet("QPushButton{\n"
		                                "background-color: None;\n"
		                                "min-width:10px;\n"
		                                "max-width:20px;\n"
		                                "min-height:10px;\n"
		                                "max-height:20px;\n"
		                                "border: None;\n"
		                                "outline: None;\n"
		                                "}")
		self.about_button.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/resources/resources/information-button.png") , QtGui.QIcon.Normal ,
		                QtGui.QIcon.Off)
		self.about_button.setIcon(icon3)
		self.about_button.setIconSize(QtCore.QSize(20 , 20))
		self.about_button.setFlat(True)
		self.about_button.setToolTip("About Developer")
		self.about_button.setObjectName("about_button")
		self.statusbar.addPermanentWidget(self.about_button)

		self.statusbar_message = QtWidgets.QLabel()
		self.statusbar_message.setText("")
		self.statusbar_message.setWordWrap(True)
		self.statusbar_message.setStyleSheet("QLabel{\n"
		                                     "color: rgb(0, 85, 127);\n"
		                                     "font: 12pt Andalus;\n"
		                                     "}")
		self.statusbar_message.setScaledContents(True)
		self.statusbar_message.setAlignment(QtCore.Qt.AlignLeft)
		self.statusbar_message.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.statusbar_message.setObjectName("statusbar_message")
		self.statusbar.addWidget(self.statusbar_message , 1)
		self.tableWidget.setStyleSheet("QHeaderView::section{"
		                             "background-color: green;\n"
		                             "alternate-background-color: red;\n"
		                                                   "}")

		self.retranslateUi(MainWindow)
		self.stackedWidget.setCurrentIndex(0)
		self.lineEdit.returnPressed.connect(self.userpassword_lineedit.setFocus)
		self.name_lineedit.returnPressed.connect(self.password_lineedit.setFocus)
		self.password_lineedit.returnPressed.connect(self.lineEdit_2.setFocus)
		self.lineEdit_3.returnPressed.connect(self.lineEdit_4.setFocus)
		self.lineEdit_4.returnPressed.connect(self.lineEdit_5.setFocus)
		self.lineEdit_5.returnPressed.connect(self.encryptdata_button.setFocus)
		self.lineEdit_2.returnPressed.connect(self.ok_button_3.setFocus)
		self.userpassword_lineedit.returnPressed.connect(self.pushButton.setFocus)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		MainWindow.setTabOrder(self.lineEdit, self.userpassword_lineedit)
		MainWindow.setTabOrder(self.userpassword_lineedit, self.pushButton)
		MainWindow.setTabOrder(self.pushButton, self.pushButton_3)
		MainWindow.setTabOrder(self.pushButton_3, self.pushButton_2)
		MainWindow.setTabOrder(self.pushButton_2, self.name_lineedit)
		MainWindow.setTabOrder(self.name_lineedit, self.password_lineedit)
		MainWindow.setTabOrder(self.password_lineedit, self.lineEdit_2)
		MainWindow.setTabOrder(self.lineEdit_2, self.ok_button_3)
		MainWindow.setTabOrder(self.ok_button_3, self.pushButton_4)
		MainWindow.setTabOrder(self.pushButton_4, self.lineEdit_3)
		MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
		MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)
		MainWindow.setTabOrder(self.lineEdit_5, self.getdata_button)
		MainWindow.setTabOrder(self.getdata_button, self.encryptdata_button)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "Password Vault"))
		self.label_5.setText(_translate("MainWindow", "Password"))
		self.pushButton.setText(_translate("MainWindow", "Login"))
		self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Email address"))
		self.label_6.setText(_translate("MainWindow", "Don\'t Have Account? Register Now"))
		self.pushButton_2.setText(_translate("MainWindow", "Sign up"))
		self.userpassword_lineedit.setPlaceholderText(_translate("MainWindow", "Enter Password"))
		self.label_7.setText(_translate("MainWindow", "Forgot Password?"))
		self.pushButton_3.setText(_translate("MainWindow", "Reset Password"))
		self.label_4.setText(_translate("MainWindow", "Email address"))
		self.name_lineedit.setPlaceholderText(_translate("MainWindow", "e.g. vault@gmail.com"))
		self.name_label.setText(_translate("MainWindow", "Enter Email Address"))
		self.ok_button_3.setText(_translate("MainWindow", "Sign up"))
		self.label_8.setText(_translate("MainWindow", "Already have account? Login"))
		self.pushButton_4.setText(_translate("MainWindow", "Sign in"))
		self.password_label.setText(_translate("MainWindow", "Enter New Password"))
		self.password_lineedit.setPlaceholderText(_translate("MainWindow", "Enter master password (Password must be 6 characters long)"))
		self.label_2.setText(_translate("MainWindow", "Confirm Password"))
		self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Re-enter password"))
		self.password_label_2.setText(_translate("MainWindow", "Password"))
		self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "e.g. Password Vault"))
		self.username_label.setText(_translate("MainWindow", "User Name"))
		self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "e.g. Gmail"))
		self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Password"))
		self.getdata_button.setText(_translate("MainWindow", "Show Passwords"))
		self.encryptdata_button.setText(_translate("MainWindow", "Save"))
		self.accountname_label.setText(_translate("MainWindow", "Account Name"))
		self.pushButton_6.setToolTip(_translate("MainWindow", "Go Back (Backspace)"))
		self.pushButton_6.setShortcut(_translate("MainWindow", "Backspace"))
		item = self.tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "Account Name"))
		item = self.tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "User Name"))
		item = self.tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "Password"))
		item = self.tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "Check & Delete"))
		self.menuOptions.setTitle(_translate("MainWindow", "Options"))
		self.actiondelete.setText(_translate("MainWindow", "Delete"))
		self.actiondelete.setShortcut(_translate("MainWindow", "Del"))
		self.actionexport.setText(_translate("MainWindow", "Export to PDF"))
		self.actionexport.setShortcut(_translate("MainWindow" , "Ctrl+P"))
		self.actionLog_out.setText(_translate("MainWindow", "Log out"))
		self.actionLog_out.setShortcut(_translate("MainWindow", "Ctrl+L"))
		self.actionExit.setText(_translate("MainWindow", "Exit"))
		self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

import vault_resources


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
